- name: Get the git commit tag
  command: git rev-parse --short HEAD
  register: git_commit_output

- name: Get the git branch name
  command: git rev-parse --abbrev-ref HEAD
  register: raw_git_branch_output

- set_fact:
    git_commit: "{{ git_commit_output.stdout }}"
    raw_git_branch: "{{ raw_git_branch_output.stdout }}"

- name: Sanitize the git branch name
  import_tasks: tasks/sanitize-branch.yml
